### ISSUE TITLE
JSONConfig.parse does not work for URLs with port other than 80

### ISSUE THREAD

**Issue by justoke** [arkhipenko/EspBootstrap#1]
Example URL:
config: http://192.168.1.175:8081/EBS3_config.json 

Serial log:
> 2020/05/21 13:52:09: [E][WiFiClient.cpp:258] connect(): socket error on fd 54, errno: 113, "Software caused connection abort"
> JSONConfig finished. rc = -1

For some reason if I use a port other than 80 in the config_url, the JSONConfig.parse method does not work and the device will keep getting stuck in a Bootstrap required cycle.

**Comment by arkhipenko** [comment]
Fixed in version 2.1.0
Please refer to README and Example 3b for details.
